name: CI

on:
  # runs on pushes to the main branch
  push:
    branches: [main]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ## Set API base URL from GitHub secrets
      NEXT_PUBLIC_API_BASE_URL: ${{secrets.NEXT_PUBLIC_API_BASE_URL}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      # install dependencies
      - run: yarn ci
      # run ESLint & Prettier
      - run: yarn run lint
      - run: yarn run prettier
      # verify that there are no type and build errors
      - run: yarn run build
      # run tests with Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
